image: golang:latest

variables:
  PROJECT: bgw

before_script:
  - mkdir -p $GOPATH/src $GOPATH/src/_/builds
  - cp -r $CI_PROJECT_DIR $GOPATH/src/$PROJECT
  - ln -s $GOPATH/src $GOPATH/src/_/builds
  - cd $GOPATH/src/$PROJECT

stages:
  - test
  - build

format:
  stage: test
  script:
    - go fmt ./...
    - go vet ./...
    - go test -race ./...

compile:
  stage: build
  script:
    - go build -race -ldflags "-extldflags '-static'" ./...


